# Dockerfile.floodlight
FROM openjdk:8-jdk

# Install necessary packages
RUN apt-get update && \
    apt-get install -y git maven curl

# Clone the Floodlight repository
RUN git clone https://github.com/floodlight/floodlight.git /floodlight

# Build Floodlight
WORKDIR /floodlight
RUN mvn clean compile assembly:single

# Expose necessary ports
EXPOSE 6653 8080

# Run Floodlight
CMD ["java", "-jar", "target/floodlight.jar"]
